### ISSUE TITLE
Schema 8.4.0"

### ISSUE THREAD

**Issue by sigurthor** [DZakh/rescript-rest#3]
What would it take to upgrade to latest version of schema ? :)

**Comment by DZakh** [comment]
You should use `8.1.0` for now. I'm really close to release `rescript-schema` v9, which will be supported by the next version of `rescript-rest`

**Comment by DZakh** [comment]
@sigurthor I released https://github.com/DZakh/rescript-rest/releases/tag/v1.1.0 with the support for `rescript-schema` v9

**Comment by sigurthor** [comment]
@DZakh  super nice, thank you!

I ran into one issue... might be my bad :) after the update

I could not use S.reverseConvertToJsonOrThrow, M.Value.map is as S.custom and it failed without calling the serializer function, but reverseConvertOrThrow works fine.
 
 "SCHEMA ERROR Failed reverse converting to JSON at ["metadata"]. Reason: The 'metdatadaValue' schema cannot be converted to JSON"

`@schema
type update={
id:string,
metadata?:  M.Value.map
}`

**Comment by DZakh** [comment]
The issue is caused by ReScript Schema not knowing how to convert `S.custom` to JSON. Instead of `S.custom` you can use `S.dict` together with `S.transform` to make it seriali to an object.
